"""
mitc4_postprocess.py
====================
Post-process Nastran SOL 101 results for the Choi & Lee (2022) clamped
plate in-plane bending benchmark generated by mitc4_plate_benchmark.py.

For each .f06 file found in the target directory the script:
  1. Reads the matching .bdf to find the Point A node ID and case metadata
     (N, mesh type, load type).
  2. Parses the F06 displacement vector for Point A (T1=U, T2=V).
  3. Selects a reference solution for error/convergence calculations:
       a. --ref-u / --ref-v  (explicit user values)
       b. --ref-from-file    (another F06 file)
       c. Auto: the regular-mesh result with the largest N >= ref_threshold
                (default 64) found in the directory — treated as fully
                converged. That case is excluded from error/convergence plots.
       d. Exact 2D elasticity formula embedded in BDF comments.
  4. Prints formatted tables (displacements, % errors, convergence slopes).
  5. Writes a plain-text summary of all displacements to results.txt.
  6. Generates convergence plots saved as PNG files.

Dependencies
------------
  matplotlib  (pip install matplotlib)
  All others: Python 3.6+ stdlib only.

Usage
-----
    python mitc4_postprocess.py results/
    python mitc4_postprocess.py results/ --ref-threshold 32
    python mitc4_postprocess.py results/ --ref-u 3.0 --ref-v -3.225
    python mitc4_postprocess.py results/ --ref-from-file results/regular_N64.f06
    python mitc4_postprocess.py results/ --no-plots
    python mitc4_postprocess.py results/ --out-dir plots/

Notes on F06 parsing
---------------------
Two header formats are recognised:
    D I S P L A C E M E N T   V E C T O R   (MSC/NX Nastran)
    D I S P L A C E M E N T S               (VIBEST and others)

Two data-row formats are accepted:
    MSC/NX:  "   123      G      1.234E+00   5.678E+00 ..."
    VIBEST:  "   123        0    1.234E+00   5.678E+00 ..."
"""

import os
import re
import sys
import math
import argparse
import textwrap
from typing import Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

class CaseResult:
    """Everything we know about one .f06 file."""
    def __init__(self):
        self.f06_path: str = ''
        self.bdf_path: Optional[str] = None
        self.stem: str = ''

        # Metadata parsed from BDF comments
        self.N: Optional[int] = None
        self.mesh_type: str = 'unknown'   # 'regular' or 'distorted'
        self.load_type: str = 'unknown'   # 'traction' or 'couple'
        self.alpha: Optional[float] = None
        self.seed: Optional[int] = None
        self.point_a_nid: Optional[int] = None

        # Exact elasticity values from BDF comments
        self.exact_u: Optional[float] = None
        self.exact_v: Optional[float] = None

        # Parsed from F06
        self.u: Optional[float] = None   # T1 at Point A
        self.v: Optional[float] = None   # T2 at Point A
        self.parse_error: Optional[str] = None

        # Set by pick_reference() — True means this case IS the reference
        self.is_reference: bool = False

    @property
    def sort_key(self):
        order = {'regular': 0, 'distorted': 1, 'unknown': 2}
        return (order.get(self.mesh_type, 9), self.load_type, self.N or 9999)


# ---------------------------------------------------------------------------
# BDF metadata parser
# ---------------------------------------------------------------------------

_RE_POINT_A   = re.compile(r'Point A.*?=\s*node\s+(\d+)', re.IGNORECASE)
_RE_EXACT_U   = re.compile(r'Exact\s+u_A\s*=\s*([+-]?\d[\d.eE+\-]*)', re.IGNORECASE)
_RE_EXACT_V   = re.compile(r'Exact\s+v_A\s*=\s*([+-]?\d[\d.eE+\-]*)', re.IGNORECASE)
_RE_BEAM_U    = re.compile(r'Beam-theory\s+u_A\s*=\s*([+-]?\d[\d.eE+\-]*)', re.IGNORECASE)
_RE_BEAM_V    = re.compile(r'Beam-theory\s+v_A\s*=\s*([+-]?\d[\d.eE+\-]*)', re.IGNORECASE)
_RE_MESH_N    = re.compile(r'Mesh:\s*(REGULAR|DISTORTED).*?N=(\d+)', re.IGNORECASE)
_RE_LOAD_TYPE = re.compile(r'Load type:\s*(traction|couple)', re.IGNORECASE)
_RE_ALPHA     = re.compile(r'alpha=([0-9.]+)')
_RE_SEED      = re.compile(r'seed=(\d+)')


def parse_bdf_metadata(bdf_path: str, result: CaseResult):
    try:
        with open(bdf_path, 'r') as f:
            for line in f:
                if not line.startswith('$'):
                    continue
                text = line[1:].strip()

                m = _RE_POINT_A.search(text)
                if m:
                    result.point_a_nid = int(m.group(1))

                for rx, attr in [(_RE_EXACT_U, 'exact_u'), (_RE_BEAM_U, 'exact_u'),
                                  (_RE_EXACT_V, 'exact_v'), (_RE_BEAM_V, 'exact_v')]:
                    if getattr(result, attr) is None:
                        m = rx.search(text)
                        if m:
                            setattr(result, attr, float(m.group(1)))

                m = _RE_MESH_N.search(text)
                if m:
                    result.mesh_type = m.group(1).lower()
                    result.N = int(m.group(2))

                m = _RE_LOAD_TYPE.search(text)
                if m:
                    result.load_type = m.group(1).lower()

                m = _RE_ALPHA.search(text)
                if m:
                    result.alpha = float(m.group(1))

                m = _RE_SEED.search(text)
                if m:
                    result.seed = int(m.group(1))

    except OSError as e:
        result.parse_error = (result.parse_error or '') + f' [BDF read error: {e}]'


# ---------------------------------------------------------------------------
# F06 displacement parser
# ---------------------------------------------------------------------------

_RE_DISP_HDR = re.compile(
    r'D\s+I\s+S\s+P\s+L\s+A\s+C\s+E\s+M\s+E\s+N\s+T\s+'
    r'(?:V\s+E\s+C\s+T\s+O\s+R|S\b)')

_RE_DISP_ROW = re.compile(
    r'^\s*(\d+)\s+'
    r'(?:G|\d+)\s+'
    r'([+-]?[\d.]+(?:[EeDd][+-]?\d+)?)\s+'
    r'([+-]?[\d.]+(?:[EeDd][+-]?\d+)?)')


def parse_f06_displacements(f06_path: str) -> Dict[int, Tuple[float, float]]:
    """Parse last displacement block; returns {nid: (T1, T2)}."""
    all_blocks: List[Dict] = []
    current_block: Optional[Dict] = None
    in_block = False

    try:
        with open(f06_path, 'r', errors='replace') as f:
            for line in f:
                if _RE_DISP_HDR.search(line):
                    if current_block:
                        all_blocks.append(current_block)
                    current_block = {}
                    in_block = True
                    continue

                if not in_block or current_block is None:
                    continue

                stripped = line.strip()
                if not stripped:
                    continue

                if any(kw in line for kw in
                       ('POINT ID', 'TYPE', 'GRID', 'COORD SYS',
                        'in global coordinate', 'SYS')):
                    continue

                m = _RE_DISP_ROW.match(line)
                if m:
                    nid = int(m.group(1))
                    t1  = float(m.group(2).replace('D', 'E').replace('d', 'e'))
                    t2  = float(m.group(3).replace('D', 'E').replace('d', 'e'))
                    current_block[nid] = (t1, t2)
                else:
                    if current_block:
                        if re.search(r'[A-Z]{4,}', stripped) or \
                           re.match(r'\s*\d+\s*$', line):
                            all_blocks.append(current_block)
                            current_block = {}
                            in_block = False
    except OSError:
        pass

    if current_block:
        all_blocks.append(current_block)
    return all_blocks[-1] if all_blocks else {}


# ---------------------------------------------------------------------------
# Directory scanner
# ---------------------------------------------------------------------------

def scan_directory(directory: str) -> List[CaseResult]:
    results = []
    f06_files = sorted(p for p in os.listdir(directory)
                       if p.lower().endswith('.f06'))
    if not f06_files:
        print(f'  No .f06 files found in {directory!r}')
        return results

    for fname in f06_files:
        stem     = fname[:-4]
        f06_path = os.path.join(directory, fname)
        bdf_path = os.path.join(directory, stem + '.bdf')
        if not os.path.exists(bdf_path):
            bdf_path = None

        r = CaseResult()
        r.f06_path = f06_path
        r.bdf_path = bdf_path
        r.stem     = stem

        # Fallback metadata from filename
        m = re.search(r'(regular|distorted)', stem, re.IGNORECASE)
        if m:
            r.mesh_type = m.group(1).lower()
        m = re.search(r'[_\-]N(\d+)', stem, re.IGNORECASE)
        if m:
            r.N = int(m.group(1))
        m = re.search(r'(traction|couple)', stem, re.IGNORECASE)
        if m:
            r.load_type = m.group(1).lower()

        if bdf_path:
            parse_bdf_metadata(bdf_path, r)

        disps = parse_f06_displacements(f06_path)

        if r.point_a_nid is None:
            r.parse_error = (r.parse_error or '') + \
                ' [Point A node ID not found in BDF]'
        elif r.point_a_nid not in disps:
            r.parse_error = (r.parse_error or '') + \
                f' [Node {r.point_a_nid} not in F06 displacement table]'
        else:
            r.u, r.v = disps[r.point_a_nid]

        results.append(r)

    results.sort(key=lambda r: r.sort_key)
    return results


# ---------------------------------------------------------------------------
# Reference selection
# ---------------------------------------------------------------------------

def pick_reference(
        results: List[CaseResult],
        ref_u: Optional[float],
        ref_v: Optional[float],
        ref_from_file: Optional[str],
        ref_threshold: int = 64,
) -> Tuple[Optional[float], Optional[float], str, Optional[CaseResult]]:
    """
    Returns (u_ref, v_ref, source_description, ref_CaseResult_or_None).

    Priority:
      1. --ref-u / --ref-v
      2. --ref-from-file
      3. Auto: regular-mesh result with largest N >= ref_threshold
      4. Exact formula from BDF comments
      5. No reference
    """
    if ref_u is not None or ref_v is not None:
        return ref_u, ref_v, 'user-supplied', None

    if ref_from_file:
        bdf_ref = ref_from_file.replace('.f06', '.bdf')
        r_tmp = CaseResult()
        r_tmp.f06_path = ref_from_file
        if os.path.exists(bdf_ref):
            parse_bdf_metadata(bdf_ref, r_tmp)
        disps = parse_f06_displacements(ref_from_file)
        if r_tmp.point_a_nid and r_tmp.point_a_nid in disps:
            u, v = disps[r_tmp.point_a_nid]
            return u, v, f'F06 file: {os.path.basename(ref_from_file)}', None
        print(f'WARNING: could not extract displacement from {ref_from_file}')

    # Auto: largest regular N >= threshold
    candidates = [r for r in results
                  if r.mesh_type == 'regular'
                  and r.N is not None and r.N >= ref_threshold
                  and r.u is not None]
    if candidates:
        ref_case = max(candidates, key=lambda r: r.N)
        ref_case.is_reference = True
        src = (f'auto: regular N={ref_case.N} '
               f'(largest N \u2265 {ref_threshold} in results)')
        return ref_case.u, ref_case.v, src, ref_case

    # Exact formula from BDF comments
    us = [r.exact_u for r in results if r.exact_u is not None]
    vs = [r.exact_v for r in results if r.exact_v is not None]
    if us:
        return us[0], (vs[0] if vs else None), \
               'exact 2D elasticity (from BDF comments)', None

    return None, None, 'none', None


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _pct(val: Optional[float], ref: Optional[float]) -> str:
    if val is None or ref is None or abs(ref) < 1e-30:
        return '    —    '
    return f'{abs(val - ref) / abs(ref) * 100:8.3f}%'


def _disp(val: Optional[float]) -> str:
    if val is None:
        return '      —      '
    return f'{val:+13.6E}'


def _slope_str(r0: CaseResult, r1: CaseResult,
               comp: str, ref: float) -> str:
    """Log-log convergence slope between two consecutive mesh sizes."""
    e0 = abs(getattr(r0, comp) - ref) if getattr(r0, comp) is not None else 0.0
    e1 = abs(getattr(r1, comp) - ref) if getattr(r1, comp) is not None else 0.0
    if e0 < 1e-30 or e1 < 1e-30 or not r0.N or not r1.N or r0.N == r1.N:
        return ''
    try:
        s = math.log(e1 / e0) / math.log(r0.N / r1.N)
        return f'{s:+.2f}'
    except (ValueError, ZeroDivisionError):
        return ''


def _short(s: str, n: int = 44) -> str:
    return s[:n] + '\u2026' if len(s) > n else s


# ---------------------------------------------------------------------------
# Console tables
# ---------------------------------------------------------------------------

def print_tables(results: List[CaseResult],
                 ref_u: Optional[float],
                 ref_v: Optional[float],
                 ref_source: str,
                 ref_case: Optional[CaseResult]):

    has_ref  = ref_u is not None or ref_v is not None
    W = 86
    WC = 28   # case-name column width

    load_types = list(dict.fromkeys(r.load_type for r in results))

    for lt in load_types:
        group  = [r for r in results if r.load_type == lt]
        active = [r for r in group if not r.is_reference]
        if not group:
            continue

        print()
        print('═' * W)
        print(f'  Load type: {lt.upper()}')
        if has_ref:
            print(f'  Reference: {ref_source}')
            if ref_u is not None:
                line = f'  u_ref = {ref_u:+.8g}'
                if ref_v is not None:
                    line += f'   v_ref = {ref_v:+.8g}'
                print(line)
        print('═' * W)

        if has_ref:
            print(f"  {'Case':<{WC}}  {'N':>4}  {'U (T1)':>13}  {'err_u':>9}  "
                  f"{'slope_u':>8}  {'V (T2)':>13}  {'err_v':>9}  {'slope_v':>8}")
            sep = (f"  {'─'*WC}  {'─'*4}  {'─'*13}  {'─'*9}  "
                   f"{'─'*8}  {'─'*13}  {'─'*9}  {'─'*8}")
        else:
            print(f"  {'Case':<{WC}}  {'N':>4}  {'U (T1)':>13}  {'V (T2)':>13}")
            sep = f"  {'─'*WC}  {'─'*4}  {'─'*13}  {'─'*13}"
        print(sep)

        # Reference row (if it came from the scanned results)
        if ref_case and ref_case in group:
            rc = ref_case
            tag = f'{rc.mesh_type}  N={rc.N}  \u2190 REFERENCE'
            if has_ref:
                print(f"  {tag:<{WC}}  {rc.N:>4}  "
                      f"{_disp(rc.u)}  {'(reference)':>9}  {'':>8}  "
                      f"{_disp(rc.v)}  {'(reference)':>9}  {'':>8}")
            else:
                print(f"  {tag:<{WC}}  {rc.N:>4}  {_disp(rc.u)}  {_disp(rc.v)}")
            print(sep)

        # Remaining cases grouped by mesh type
        for mesh in ('regular', 'distorted', 'unknown'):
            mesh_cases = sorted(
                [r for r in active if r.mesh_type == mesh],
                key=lambda r: r.N or 0)
            if not mesh_cases:
                continue

            for idx, r in enumerate(mesh_cases):
                name = f'{r.mesh_type}  N={r.N}' if r.N else r.stem[:WC]
                if r.parse_error:
                    name += ' !'

                su = sv = ''
                if has_ref and idx > 0 and mesh == 'regular':
                    prev = mesh_cases[idx - 1]
                    if ref_u is not None and r.u is not None and prev.u is not None:
                        su = _slope_str(prev, r, 'u', ref_u)
                    if ref_v is not None and r.v is not None and prev.v is not None:
                        sv = _slope_str(prev, r, 'v', ref_v)

                if has_ref:
                    print(f"  {name:<{WC}}  {str(r.N or '?'):>4}  "
                          f"{_disp(r.u)}  {_pct(r.u, ref_u)}  {su:>8}  "
                          f"{_disp(r.v)}  {_pct(r.v, ref_v)}  {sv:>8}")
                else:
                    print(f"  {name:<{WC}}  {str(r.N or '?'):>4}  "
                          f"{_disp(r.u)}  {_disp(r.v)}")

                if r.parse_error:
                    print(f"  {'':>{WC}}       *** {r.parse_error.strip()}")

            print()   # blank row between mesh groups

    print()


# ---------------------------------------------------------------------------
# Text file
# ---------------------------------------------------------------------------

def write_results_txt(results: List[CaseResult],
                      ref_u: Optional[float],
                      ref_v: Optional[float],
                      ref_source: str,
                      ref_case: Optional[CaseResult],
                      out_path: str):
    W = 80
    lines = ['=' * W,
             'MITC4 BENCHMARK — POINT A DISPLACEMENTS',
             '=' * W,
             'Generated by mitc4_postprocess.py',
             f'Reference source: {ref_source}']
    if ref_u is not None:
        lines.append(f'  u_ref = {ref_u:+.10g}')
    if ref_v is not None:
        lines.append(f'  v_ref = {ref_v:+.10g}')
    if ref_case:
        lines.append(f'  (N={ref_case.N} regular mesh used as reference; '
                     f'excluded from error columns)')
    lines.append('')

    PAPER = {2:  (19.12, 7.59, 11.53, 23.29, 6.96,  9.53),
             4:  ( 6.92, 3.96,  0.44,  6.08, 2.95,  1.37),
             8:  ( 2.28, 1.38,  0.25,  1.93, 1.04,  0.09),
             16: ( 0.78, 0.34,  0.12,  0.83, 0.42,  0.08)}
    lines.append('Paper error tables (Choi & Lee 2022, distorted mesh, % error vs 64x64):')
    lines.append(f'  {"N":>4}  {"u:Q4":>8}  {"u:MITC4":>9}  {"u:Impr":>8}'
                 f'  {"v:Q4":>8}  {"v:MITC4":>9}  {"v:Impr":>8}')
    lines.append('  ' + '-' * 62)
    for N, v in sorted(PAPER.items()):
        lines.append(f'  {N:>4}  {v[0]:>7.2f}%  {v[1]:>8.2f}%  {v[2]:>7.2f}%'
                     f'  {v[3]:>7.2f}%  {v[4]:>8.2f}%  {v[5]:>7.2f}%')
    lines += ['', '=' * W, 'RESULTS', '=' * W, '']

    load_types = list(dict.fromkeys(r.load_type for r in results))
    for lt in load_types:
        group  = [r for r in results if r.load_type == lt]
        active = [r for r in group if not r.is_reference]

        lines.append(f'--- Load type: {lt} ---')
        lines.append('')

        hdr = (f'  {"File":<36}  {"N":>4}  {"mesh":>10}  '
               f'{"U (T1)":>13}  {"V (T2)":>13}  '
               f'{"err_u%":>9}  {"slope_u":>8}  {"err_v%":>9}  {"slope_v":>8}')
        lines += [hdr, '  ' + '-' * (len(hdr) - 2)]

        if ref_case and ref_case in group:
            rc = ref_case
            lines.append(
                f'  {os.path.basename(rc.f06_path):<36}  {rc.N:>4}  '
                f'{rc.mesh_type:>10}  {_disp(rc.u)}  {_disp(rc.v)}'
                f'  {"(ref)":>9}  {"":>8}  {"(ref)":>9}  {"":>8}')
            lines.append('  ' + '-' * (len(hdr) - 2))

        for mesh in ('regular', 'distorted', 'unknown'):
            mesh_cases = sorted(
                [r for r in active if r.mesh_type == mesh],
                key=lambda r: r.N or 0)
            prev = None
            for r in mesh_cases:
                fname = os.path.basename(r.f06_path)[:36]
                eu = _pct(r.u, ref_u).strip() if ref_u is not None else '—'
                ev = _pct(r.v, ref_v).strip() if ref_v is not None else '—'
                su = sv = ''
                if prev is not None and mesh == 'regular':
                    if ref_u is not None and r.u is not None and prev.u is not None:
                        su = _slope_str(prev, r, 'u', ref_u)
                    if ref_v is not None and r.v is not None and prev.v is not None:
                        sv = _slope_str(prev, r, 'v', ref_v)
                lines.append(
                    f'  {fname:<36}  {str(r.N or "?"):>4}  {r.mesh_type:>10}  '
                    f'{_disp(r.u)}  {_disp(r.v)}  '
                    f'{eu:>9}  {su:>8}  {ev:>9}  {sv:>8}')
                if r.parse_error:
                    lines.append(f'    ERROR: {r.parse_error.strip()}')
                prev = r
            if mesh_cases:
                lines.append('')

    lines += ['=' * W, 'RAW VALUES (full precision)', '=' * W]
    for r in results:
        tag = ' [REFERENCE]' if r.is_reference else ''
        lines += [f'{r.stem}{tag}:',
                  f'  Point A node = {r.point_a_nid}',
                  f'  U (T1) = {r.u!r}',
                  f'  V (T2) = {r.v!r}']
        if r.parse_error:
            lines.append(f'  ERRORS: {r.parse_error.strip()}')
    lines.append('')

    with open(out_path, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'Results written to: {out_path}')


# ---------------------------------------------------------------------------
# Plots
# ---------------------------------------------------------------------------

def make_plots(results: List[CaseResult],
               ref_u: Optional[float],
               ref_v: Optional[float],
               ref_source: str,
               ref_case: Optional[CaseResult],
               out_dir: str):
    try:
        import matplotlib
        matplotlib.use('Agg')
        import matplotlib.pyplot as plt
    except ImportError:
        print('WARNING: matplotlib not available — skipping plots.')
        print('         Install with: pip install matplotlib')
        return

    os.makedirs(out_dir, exist_ok=True)

    C_REG   = '#2166ac'
    C_DIST  = '#d6604d'
    C_REF   = '#1a1a1a'
    C_PAPER = '#888888'
    C_SLOPE = '#cccccc'
    MK_REG  = 'o'
    MK_DIST = 's'

    load_types = list(dict.fromkeys(r.load_type for r in results))

    for lt in load_types:
        group    = [r for r in results if r.load_type == lt]
        plotable = [r for r in group if not r.is_reference]

        regular   = sorted([r for r in plotable
                             if r.mesh_type == 'regular' and r.N and r.u is not None],
                            key=lambda r: r.N)
        distorted = sorted([r for r in plotable
                             if r.mesh_type == 'distorted' and r.N and r.u is not None],
                            key=lambda r: r.N)

        if not regular and not distorted:
            continue

        suffix = f'_{lt}' if len(load_types) > 1 else ''

        # ── Plot 1: absolute displacements vs N ──────────────────────────────
        fig, axes = plt.subplots(1, 2, figsize=(12, 5))
        fig.suptitle(
            f'Point A Displacements — {lt.capitalize()} load\n'
            f'Choi & Lee (2022) Benchmark',
            fontsize=13, fontweight='bold', y=1.01)

        for ax, comp, ref_val, ylabel in [
                (axes[0], 'u', ref_u, 'U  (horizontal, T1)'),
                (axes[1], 'v', ref_v, 'V  (vertical,   T2)')]:

            Ns_r = [r.N for r in regular]
            Vs_r = [getattr(r, comp) for r in regular]
            Ns_d = [r.N for r in distorted]
            Vs_d = [getattr(r, comp) for r in distorted]

            if Ns_r:
                ax.plot(Ns_r, Vs_r, color=C_REG, marker=MK_REG,
                        linewidth=1.8, markersize=7, label='Regular mesh')
            if Ns_d:
                ax.plot(Ns_d, Vs_d, color=C_DIST, marker=MK_DIST,
                        linewidth=1.8, markersize=7, linestyle='--',
                        label='Distorted mesh')

            if ref_val is not None:
                ax.axhline(ref_val, color=C_REF, linewidth=1.2, linestyle=':',
                           label=f'Reference ({_short(ref_source, 28)})')
            if ref_case and ref_case.load_type == lt:
                rv = getattr(ref_case, comp)
                if rv is not None:
                    ax.plot(ref_case.N, rv, marker='*', markersize=14,
                            color=C_REF, zorder=5,
                            label=f'N={ref_case.N} (reference)')

            for r in regular + distorted:
                val = getattr(r, comp)
                if val is not None:
                    ax.annotate(f'{val:.4f}', xy=(r.N, val),
                                xytext=(4, 4), textcoords='offset points',
                                fontsize=7.5, color='#444444')

            all_Ns = sorted(set(Ns_r + Ns_d))
            ax.set_xlabel('Mesh size  N', fontsize=11)
            ax.set_ylabel(ylabel, fontsize=11)
            ax.set_title(ylabel, fontsize=11)
            ax.legend(fontsize=9, loc='best')
            ax.grid(True, linestyle=':', alpha=0.5)
            if all_Ns:
                ax.set_xticks(all_Ns)

        fig.tight_layout()
        path = os.path.join(out_dir, f'displacements{suffix}.png')
        fig.savefig(path, dpi=150, bbox_inches='tight')
        plt.close(fig)
        print(f'  Plot saved: {path}')

        # ── Plot 2: log-log convergence ───────────────────────────────────────
        if ref_u is None and ref_v is None:
            continue

        PAPER_U = {2: 19.12, 4: 6.92, 8: 2.28, 16: 0.78}
        PAPER_V = {2: 23.29, 4: 6.08, 8: 1.93, 16: 0.83}

        fig, axes = plt.subplots(1, 2, figsize=(12, 5))
        fig.suptitle(
            f'Convergence — Relative Error at Point A\n'
            f'{lt.capitalize()} load  |  Ref: {_short(ref_source, 50)}',
            fontsize=13, fontweight='bold', y=1.01)

        for ax, comp, ref_val, paper_errs, ylabel in [
                (axes[0], 'u', ref_u, PAPER_U,
                 '|u_h \u2212 u_ref| / |u_ref|  (%)'),
                (axes[1], 'v', ref_v, PAPER_V,
                 '|v_h \u2212 v_ref| / |v_ref|  (%)')]:

            if ref_val is None or abs(ref_val) < 1e-30:
                ax.text(0.5, 0.5, 'No reference value',
                        transform=ax.transAxes, ha='center', va='center',
                        fontsize=11, color='#888888')
                continue

            def err_pts(cases):
                return [(1.0 / r.N,
                         abs(getattr(r, comp) - ref_val) / abs(ref_val) * 100)
                        for r in cases
                        if getattr(r, comp) is not None and r.N]

            errs_r = err_pts(regular)
            errs_d = err_pts(distorted)

            if errs_r:
                xs, ys = zip(*errs_r)
                ax.loglog(xs, ys, color=C_REG, marker=MK_REG,
                          linewidth=1.8, markersize=7, label='Regular mesh')
                for (x, y), r in zip(errs_r, regular):
                    ax.annotate(f'N={r.N}', xy=(x, y),
                                xytext=(4, 4), textcoords='offset points',
                                fontsize=7.5, color='#444444')

            if errs_d:
                xs, ys = zip(*errs_d)
                ax.loglog(xs, ys, color=C_DIST, marker=MK_DIST,
                          linewidth=1.8, markersize=7, linestyle='--',
                          label='Distorted mesh')
                for (x, y), r in zip(errs_d, distorted):
                    ax.annotate(f'N={r.N}', xy=(x, y),
                                xytext=(4, -10), textcoords='offset points',
                                fontsize=7.5, color='#444444')

            # Paper Q4 curve
            paper_pts = sorted((1.0 / N, e) for N, e in paper_errs.items())
            if paper_pts:
                xs_p, ys_p = zip(*paper_pts)
                ax.loglog(xs_p, ys_p, color=C_PAPER, marker='^',
                          linewidth=1.2, markersize=6, linestyle='-.',
                          label='Paper: Q4 (Choi & Lee)')

            # O(h²) slope guide
            all_pts = errs_r + errs_d
            if len(all_pts) >= 2:
                spts = sorted(all_pts)
                hm, em = spts[len(spts) // 2]
                h_lo = min(x for x, _ in all_pts) * 0.7
                h_hi = max(x for x, _ in all_pts) * 1.4
                ax.loglog([h_lo, h_hi],
                          [em * (h_lo / hm) ** 2, em * (h_hi / hm) ** 2],
                          color=C_SLOPE, linewidth=1.0, linestyle='--',
                          label='O(h\u00b2) slope')

            ax.set_xlabel('Element size  h = 1/N', fontsize=11)
            ax.set_ylabel(ylabel, fontsize=10)
            ax.set_title(f'{comp.upper()} error vs mesh size', fontsize=11)
            ax.legend(fontsize=9, loc='best')
            ax.grid(True, which='both', linestyle=':', alpha=0.4)

        fig.tight_layout()
        path = os.path.join(out_dir, f'convergence{suffix}.png')
        fig.savefig(path, dpi=150, bbox_inches='tight')
        plt.close(fig)
        print(f'  Plot saved: {path}')

        # ── Plot 3: error bar chart ───────────────────────────────────────────
        ns_all = sorted(set(r.N for r in plotable if r.N and r.u is not None))
        if not ns_all:
            continue

        fig, axes = plt.subplots(1, 2, figsize=(12, 5))
        fig.suptitle(
            f'Relative Error at Point A\n'
            f'{lt.capitalize()} load  |  Ref: {_short(ref_source, 50)}',
            fontsize=13, fontweight='bold', y=1.01)

        bar_w = 0.35

        for ax, comp, ref_val, ylabel in [
                (axes[0], 'u', ref_u, '|u_h \u2212 u_ref| / |u_ref|  (%)'),
                (axes[1], 'v', ref_v, '|v_h \u2212 v_ref| / |v_ref|  (%)')]:

            if ref_val is None or abs(ref_val) < 1e-30:
                ax.text(0.5, 0.5, 'No reference value',
                        transform=ax.transAxes, ha='center', va='center',
                        fontsize=11, color='#888888')
                continue

            def get_err(cases, N):
                r = next((x for x in cases if x.N == N), None)
                if r is None or getattr(r, comp) is None:
                    return None
                return abs(getattr(r, comp) - ref_val) / abs(ref_val) * 100

            xs = list(range(len(ns_all)))
            errs_r_bar = [get_err(regular,   N) for N in ns_all]
            errs_d_bar = [get_err(distorted, N) for N in ns_all]

            rects_r = ax.bar([x - bar_w / 2 for x in xs],
                             [v or 0 for v in errs_r_bar], bar_w,
                             color=C_REG,  alpha=0.85, label='Regular',   zorder=3)
            rects_d = ax.bar([x + bar_w / 2 for x in xs],
                             [v or 0 for v in errs_d_bar], bar_w,
                             color=C_DIST, alpha=0.85, label='Distorted', zorder=3)

            for rect, val in (list(zip(rects_r, errs_r_bar)) +
                              list(zip(rects_d, errs_d_bar))):
                if val:
                    ax.text(rect.get_x() + rect.get_width() / 2.,
                            rect.get_height() * 1.02,
                            f'{val:.2f}%', ha='center', va='bottom',
                            fontsize=7.5)

            ax.set_xlabel('Mesh size  N', fontsize=11)
            ax.set_ylabel(ylabel, fontsize=10)
            ax.set_title(f'{comp.upper()} relative error', fontsize=11)
            ax.set_xticks(xs)
            ax.set_xticklabels([str(N) for N in ns_all])
            ax.legend(fontsize=9)
            ax.grid(True, axis='y', linestyle=':', alpha=0.4, zorder=0)

        fig.tight_layout()
        path = os.path.join(out_dir, f'error_bars{suffix}.png')
        fig.savefig(path, dpi=150, bbox_inches='tight')
        plt.close(fig)
        print(f'  Plot saved: {path}')


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description='Post-process Nastran F06 results for the Choi & Lee (2022) '
                    'clamped plate benchmark.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""
        Reference priority
        ------------------
          1. --ref-u / --ref-v         explicit displacement values
          2. --ref-from-file           specific F06 file
          3. auto (default)            largest regular N >= --ref-threshold
                                       (default: 64) found in the directory;
                                       that case is excluded from error plots
                                       and labelled REFERENCE in all output
          4. exact 2D elasticity       formula embedded in BDF comments

        Examples
        --------
          python mitc4_postprocess.py results/
          python mitc4_postprocess.py results/ --ref-threshold 32
          python mitc4_postprocess.py results/ --ref-u 3.0 --ref-v -3.225
          python mitc4_postprocess.py results/ --ref-from-file results/regular_N64.f06
          python mitc4_postprocess.py results/ --no-plots
        """))

    parser.add_argument('directory',
                        help='Directory containing .f06 (and optionally .bdf) files')
    parser.add_argument('--ref-u', type=float, default=None,
                        help='Reference U displacement at Point A')
    parser.add_argument('--ref-v', type=float, default=None,
                        help='Reference V displacement at Point A')
    parser.add_argument('--ref-from-file', default=None,
                        help='F06 file to use as the reference solution')
    parser.add_argument('--ref-threshold', type=int, default=64,
                        help='Minimum N for auto-reference (default: 64)')
    parser.add_argument('--no-plots', action='store_true',
                        help='Skip plot generation')
    parser.add_argument('--out-dir', default=None,
                        help='Output directory (default: same as input directory)')
    parser.add_argument('--out-txt', default='results.txt',
                        help='Name of the text summary file (default: results.txt)')

    args = parser.parse_args()

    if not os.path.isdir(args.directory):
        print(f'ERROR: {args.directory!r} is not a directory.')
        sys.exit(1)

    out_dir = args.out_dir or args.directory

    print(f'\nScanning {args.directory!r} for .f06 files ...\n')
    results = scan_directory(args.directory)
    if not results:
        print('No results found.')
        sys.exit(0)

    print(f'Found {len(results)} result file(s):\n')
    for r in results:
        status = 'OK' if r.u is not None else 'ERR'
        print(f'  [{status}]  {os.path.basename(r.f06_path):<45}  '
              f'mesh={r.mesh_type}  N={r.N}  load={r.load_type}')

    ref_u, ref_v, ref_source, ref_case = pick_reference(
        results, args.ref_u, args.ref_v,
        args.ref_from_file, args.ref_threshold)

    print()
    print(f'Reference: {ref_source}')
    if ref_u is not None:
        print(f'  u_ref = {ref_u:+.8g}')
    if ref_v is not None:
        print(f'  v_ref = {ref_v:+.8g}')
    if ref_case:
        print(f'  (N={ref_case.N} case excluded from error/convergence columns)')

    print_tables(results, ref_u, ref_v, ref_source, ref_case)

    os.makedirs(out_dir, exist_ok=True)
    txt_path = os.path.join(out_dir, args.out_txt)
    write_results_txt(results, ref_u, ref_v, ref_source, ref_case, txt_path)

    if not args.no_plots:
        print('\nGenerating plots ...')
        make_plots(results, ref_u, ref_v, ref_source, ref_case, out_dir)

    print('\nDone.')


if __name__ == '__main__':
    main()
